### ISSUE TITLE
Unable to scan blueprints

### ISSUE THREAD

**Issue by andjsch** [ryanmitchell/statamic-translation-manager#14]
**Expected behavior:**
I'd expect some screen to appear

**Actual behavior:**
If I click scan blueprints, an error is thrown: https://flareapp.io/share/q5Yqxvx5

**Version:**
Environment
Application Name: BTU Forms
Laravel Version: 10.39.0
PHP Version: 8.3.0
Composer Version: 2.5.8
Environment: local
Debug Mode: ENABLED
URL: btu-forms.test
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: null
Cache: statamic
Database: sqlite
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Locales
Installed
LaravelLang\Actions\Plugin: 1.4.1
LaravelLang\Attributes\Plugin: 2.9.1
LaravelLang\HttpStatuses\Plugin: 3.8.0
LaravelLang\Lang\Plugin: 13.12.0
Locales Version: 1.9.0
Protected
Publisher Version: 15.0.2

Statamic
Addons: 5
Antlers: runtime
Stache Watcher: Disabled
Static Caching: Disabled
Version: 4.42.1 PRO

Statamic Addons
ryanmitchell/statamic-translation-manager: 1.2.2
studio1902/statamic-peak-browser-appearance: 3.3.4
studio1902/statamic-peak-commands: 2.7.0
studio1902/statamic-peak-seo: 7.5.0
studio1902/statamic-peak-tools: 4.2.0

**Comment by ryanmitchell** [comment]
Yep it's coming from the default peak install - Rob mentioned it to be and it's on my list to look at when I get some time. Feel free to dig into it if its urgent for you.

**Comment by ryanmitchell** [comment]
This is fixed in v1.2.3
