### ISSUE TITLE
Error could not find driver on productive instance

### ISSUE THREAD

**Issue by thomas4Bitcraft** [ryanmitchell/statamic-translation-manager#18]
It works locally but as soon as I deploy it I get this error when calling the `/cp/translations` path:

<img width="1365" alt="image" src="https://github.com/ryanmitchell/statamic-translation-manager/assets/44415527/5e052c6d-855c-47c4-94c2-0654347d64fd">

**Comment by ryanmitchell** [comment]
The add-on requires SQLite, the server doesnt seem to have support installed for it

**Comment by arapmelly** [comment]
> The add-on requires SQLite, the server doesnt seem to have support installed for it

Enabling sqlite as database driver worked for me. 

@ryanmitchell how can one enable MySQL or generally the eloquent driver.

**Comment by ryanmitchell** [comment]
This add on uses an internal SQLite database. Eloquent support isn’t possible. 

if you are asking how to use the eloquent driver generally see: https://github.com/statamic/eloquent-driver

**Comment by arapmelly** [comment]
I went through the code and found it's using Sushi hence the need for sqlite. I'm trying to see if it's possible to use a different storage for this. i.e. MySQL, Redis etc.

**Comment by ryanmitchell** [comment]
To be honest, I wouldn't be interested in supporting eloquent on this add-on. The purpose of using Sushi was it does a real time flat tile to simple eloquent transition. I don't think requiring SQLite is a big issue, its a very common PHP addon available on most installs.
