### ISSUE TITLE
Feature: Dynamic translations stay dynamic on saving

### ISSUE THREAD

**Issue by marcorieser** [ryanmitchell/statamic-translation-manager#24]
**Expected behavior:**
When having e.g. `'form_mail_url' => config('app.url'),` in `lang/de/strings.png` and you save within the Translations Manager the evaluated value e.g. `https://awesomesite.tld` gets saved.

**Actual behavior:**
The saved value would stay as `config('app.url')`.

**Comment by marcorieser** [comment]
Hm, was just thinking that the dynamic part should get injected into the translation as param like:
`'form_mail_url' => ':url',`

Please feel free to close that if you agree with that comment 🙈

**Comment by ryanmitchell** [comment]
Yeah it should use the laravel `:xxx` convention really.
