### ISSUE TITLE
Just installed this packed, hit the scan blueprints this is the error I get

### ISSUE THREAD

**Issue by kobe-f8** [ryanmitchell/statamic-translation-manager#7]
https://flareapp.io/share/J7oK2947

**Comment by ryanmitchell** [comment]
I've tagged 1.1.1 which should solve this

**Comment by kobe-f8** [comment]
Awesome, that fixed it! Also, thank you so so much for this plugin, it's something I wished existed years ago! ❤️

**Comment by ryanmitchell** [comment]
You're welcome!
